name: Deploy to Azure

on:
  push:
    branches:
      - main
      
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
        audience: api://AzureADTokenExchange

    - name: Verify Azure Login
      run: |
        az account show --output table
        # Example commands
        az group list --output table
        az vm list --output table

    - name: Delete expired secrets
      run: |
        az ad app credential reset --id e62844f4-ae87-4dc4-97cb-75677079ac8e --end-date $(date -d "+90 days" +"%Y-%m-%d") --append
        # Set the current date in ISO 8601 format
        # current_date=$(date -u +%Y-%m-%dT%H:%M:%SZ)
        
        # # List expired secrets
        # expired_secrets=$(az ad app credential list --id e62844f4-ae87-4dc4-97cb-75677079ac8e --query "[?endDate < '$current_date'].[id]" -o tsv)
        
        # # Delete each expired secret
        # for secret_id in $expired_secrets; do
        #   echo "Deleting secret: $secret_id"
        #   az ad app credential delete --id e62844f4-ae87-4dc4-97cb-75677079ac8e --key-id $secret_id
        # done
