name: Deploy to Azure

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Azure login
      uses: azure/login@v2
      with:
        enable-oidc: true
        auth-type: IDENTITY
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    - name: Verify Azure Login
      run: |
        az account show --output table
        # Example commands
        az group list --output table
        az vm list --output table
        # Add other commands as needed
