name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Azure CLI
      uses: azure/setup-azure-cli@v1
      with:
        azure-cliversion: 'latest'

    - name: Log in to Azure using Federated Credentials
      id: azure_login
      uses: azure/login@v2
      with:
        enable-oidc: true
        # This is sufficient for OIDC-based authentication

    - name: Verify Azure Login
      run: |
        az account show --output table
        # Example commands
        az group list --output table
        az vm list --output table
        # Add other commands as needed
